POST http://localhost:3000/users
Content-Type: application/json

{
    "name" : "Kosuru Thrishik",
    "username" : "Thrishik",
    "password" : "1000363",
    "gender" : "Male",
    "location" : "Nellore"

}
###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username" : "Thrishik",
    "password" : "1000363"
    
}

###

GET http://localhost:3000/districts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRocmlzaGlrIiwiaWF0IjoxNjkyNDU0OTIzfQ._3Zi3-WN7CV5OFXq8TXiXMcuPdM0Y-j89wvMipboF0g











